fix requirements

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,8 +1,10 @@
-name: Run Tests on Pull Request
+name: Laravel Log Cleaner Tests
 
 on:
+  push:
+    branches: [ "main" ]
   pull_request:
-    branches: [ main ]
+    branches: [ "main" ]
 
 jobs:
   test:
@@ -10,8 +12,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        php: [ 7.4, 8.0, 8.1, 8.2 ]
-        laravel: [ 7.*, 8.*, 9.*, 10.*,11.* ]
+        php: [7.4, 8.0, 8.1, 8.2]
+        laravel: [7.*, 8.*, 9.*, 10.*,11.*]
         exclude:
           - php: 7.4
             laravel: 9.*
@@ -22,38 +24,49 @@ jobs:
           - php: 8.0
             laravel: 7.*
 
-
-    name: PHP ${{ matrix.php-version }} - Laravel ${{ matrix.laravel-version }}
+    name: P${{ matrix.php }} - L${{ matrix.laravel }}
 
     steps:
       - uses: actions/checkout@v3
+
       - name: Setup PHP
-        uses: shivammathur/setup-php@v3
+        uses: shivammathur/setup-php@v2
         with:
-          php-version: ${{ matrix.php-version }}
-          extensions: mbstring, dom, fileinfo
-          coverage: xdebug
+          php-version: ${{ matrix.php }}
+          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
+          coverage: none
 
-      - name: Get composer cache directory
-        id: composer-cache
-        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
-
-      - name: Cache composer dependencies
-        uses: actions/cache@v3
-        with:
-          path: ${{ steps.composer-cache.outputs.dir }}
-          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
-          restore-keys: ${{ runner.os }}-composer-
-
-      - name: Install Composer dependencies
+      - name: Install dependencies
         run: |
-          composer require "laravel/framework:${{ matrix.laravel-version }}" --no-interaction --no-update
+          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
           composer update --prefer-dist --no-interaction --no-progress
 
-      - name: Show installed versions
+      - name: Create Laravel Project
         run: |
-          php --version
-          composer show laravel/framework
+          composer create-project --prefer-dist laravel/laravel:${{ matrix.laravel }} test-app
+          cd test-app
+          composer require jiordiviera/laravel-log-cleaner
 
-      - name: Run test suite
+      - name: Generate Log Files
+        run: |
+          cd test-app
+          php artisan tinker --execute="Log::info('Test log entry');"
+          php artisan tinker --execute="Log::error('Test error entry');"
+
+      - name: Run Log Cleaner
+        run: |
+          cd test-app
+          php artisan log:clear
+
+      - name: Check Log Files
+        run: |
+          cd test-app/storage/logs
+          if [ -s laravel.log ]; then
+            echo "Log file is not empty"
+            exit 1
+          else
+            echo "Log file is empty or does not exist"
+          fi
+
+      - name: Run Package Tests
         run: vendor/bin/pest
